version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/usr/src/app
    command: sh -c "cd vercel-nextjs-ts-app && npm run dev"
    ports:
      - "3000:3000"
