import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
// import Link from 'next/link'
// import styles from "../styles/Home.module.css";
import { getSortedPostsData, Post } from "@/lib/posts";
import { GetStaticProps } from "next";

type HomeProps = {
  posts: Post[];
};

export const getStaticProps: GetStaticProps = async () => {
  console.log(`env_test:${process.env.FOO}`);
  console.log(`env_test(NEXT_PUBLIC):${process.env.NEXT_PUBLIC_FOO}`);
  const posts = getSortedPostsData();
  return {
    props: {
      posts,
    },
  };
};

const Home: NextPage<HomeProps> = (props) => {
  const { posts } = props;
  // console.log(props);

  return (
    <div className="">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="text-2xl text-center">
        <h1 className="text-6xl font-bold">
          Welcome to{" "}
          <a className="text-blue-600" href="https://nextjs.org">
            Next.js!
          </a>
        </h1>

        <section className="text-2xl text-center">
          <p className="text-red-600">Hoge</p>
          <h1>.env test</h1>
          {/* <p>env:{process.env.FOO}</p> */}
          <p>next_public:{process.env.NEXT_PUBLIC_FOO}</p>
        </section>
        <section className="">
          <h2 className="">List</h2>
          <ul className="">
            {props.posts.map((post) => (
              <li className="" key={post.id}>
                {post.id}: {post.title}: {post.date}
              </li>
            ))}
          </ul>
        </section>
      </main>

      <footer className=""></footer>
    </div>
  );
};

export default Home;
