import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
// import Link from 'next/link'
import styles from "../styles/Home.module.css";
import { getSortedPostsData, Post } from "../lib/posts";
import { GetStaticProps } from "next";

type HomeProps = {
  posts: Post[];
};

export const getStaticProps: GetStaticProps = async () => {
  console.log(`env_test:${process.env.FOO}`);
  console.log(`env_test(NEXT_PUBLIC):${process.env.NEXT_PUBLIC_FOO}`);
  const posts = getSortedPostsData();
  return {
    props: {
      posts,
    },
  };
};

const Home: NextPage<HomeProps> = (props) => {
  const { posts } = props;
  // console.log(props);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <section className={styles.headingMd}>
          <p>Hoge</p>
          <h1>.env test</h1>
          {/* <p>env:{process.env.FOO}</p> */}
          <p>next_public:{process.env.NEXT_PUBLIC_FOO}</p>
        </section>
        <section className={`${styles.headingMd} ${styles.padding1px}`}>
          <h2 className={styles.headingLg}>List</h2>
          <ul className={styles.list}>
            {props.posts.map((post) => (
              <li className={styles.listItem} key={post.id}>
                {post.id}: {post.title}: {post.date}
              </li>
            ))}
          </ul>
        </section>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
};

export default Home;
